config/routes.rb
Pronosticos::Application.routes.draw do

  namespace :alumnado do
    match 'pronosticos/' => 'pronosticos#index', :via => :get
    match 'pronosticos/create' => 'pronosticos#create', :via => :post
    match 'pronosticos/thank_you' => 'pronosticos#thank_you'
    match 'pronosticos/changetoadmin' => 'pronosticos#changetoadmin'
  end

  match '/settings' => 'settings#index', :via  => :get, :as => :settings
  match 'main/login' => 'main#login', :via => :get, :as => :login
  match 'admin/logout' => 'admin#logout', :via => :get, :as => :logout

	root :to => "main#login"
  match ':controller(/:action(/:id(.:format)))'

end

app/views/shared/_header_top.html.erb
<div id="header_top">
	<div class="wrapper">
		<div id="user_info">
			<%= @user.full_name unless @user.nil? %> | <%= link_to 'Configuraci&oacute;n'.html_safe, settings_url %> | <%= link_to 'Salir', logout_url %>
			<% if session[:true_user_id] %>
				| <%= link_to "Back to admin", :controller => :pronosticos, :action => :changetoadmin%>
			<% end %>
		</div>
		<div class="clr"></div>
	</div>
</div>

app/views/shared/_js.html.erb
<%= javascript_include_tag 'jquery.js' %>
<%= javascript_include_tag 'global_functions.js' %>

app/views/shared/_main_header.html.erb
<% caption = caption.nil? ? '' : caption %>
<% title = title.nil? ? '' : title %>
<div id="main_header">
	<div id="header_left"></div>
	<div id="header_right">	
		<span class="big"><%= truncate title, :length => 25 %></span><br />		
		<span class="medium"><%= caption %></span>			
	</div>
	<div class="clr"></div>
</div>

app/views/shared/_meta.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<meta name="author" content="Instituto Tecnologico y de Estudios Superiores de Monterrey" />
<meta name="description" content="Sistema de pronósticos académicos para alumnos del Campus Santa Fe." />
<meta name="keywords" content="ITESM, Tec de Monterrey, CSF, pronosticos" />

app/views/shared/_nav.html.erb
<div id="nav">
	<div class="wrapper">
		<ul>
			<li class="first">
				<%= link_to 'Home', :controller => :admin, :action => :index %>
			</li>
			<li>
				<%= link_to 'Alumnos', :controller => :alumnos, :action => :index %>
			</li>
			<li>
				<%= link_to 'Materias', :controller => :materias, :action => :index %>
			</li>
			<li>
				<%= link_to 'Carreras', :controller => :carreras, :action => :index %>
			</li>
			<% unless @user.is_director? %>
				<li>
					<%= link_to 'Directores', :controller => :directores, :action => :index %>
				</li>
			<% end %>
			<li>
				<%= link_to 'Planes de estudio', :controller => :planes, :action => :index %>
			</li>
			<li>
				<%= link_to 'Semestres', :controller => :semestres, :action => :index %>
			</li>
			<li class="last">
				<%= link_to 'Pronósticos', :controller => :pronosticos, :action => :index %>
			</li>
			<div class="clr"></div>
		</ul>
	</div>
</div>

app/views/shared/_stylesheets.html.erb
<%= stylesheet_link_tag 'reset.css' %>
<%= stylesheet_link_tag 'pronosticos.css' %>