config/routes.rb
Pronosticos::Application.routes.draw do

  namespace :alumnado do
    match 'pronosticos/' => 'pronosticos#index', :via => :get
    match 'pronosticos/create' => 'pronosticos#create', :via => :post
    match 'pronosticos/thank_you' => 'pronosticos#thank_you'
    match 'pronosticos/changetoadmin' => 'pronosticos#changetoadmin'
  end

  match '/settings' => 'settings#index', :via  => :get, :as => :settings
  match 'main/login' => 'main#login', :via => :get, :as => :login
  match 'admin/logout' => 'admin#logout', :via => :get, :as => :logout

	root :to => "main#login"
  match ':controller(/:action(/:id(.:format)))'

end

app/models/pronostico.rb
class Pronostico < ActiveRecord::Base
  scope :total_count, select("COUNT(*) AS num, pronosticos.materia_id, materias.clave, materias.nombre").joins("JOIN materias ON materias.id = pronosticos.materia_id").group("pronosticos.materia_id, materias.clave, materias.nombre").order("num DESC")  
                 
  scope :by_plan_id, lambda { |plan_id| where("pronosticos.alumno_id IN (SELECT id FROM alumnos WHERE alumnos.plane_id IN (?))", plan_id) }
  scope :with_alumno, select("usuarios.nombre, usuarios.apellidos, usuarios.username, alumnos.id AS alumno_id").joins("JOIN alumnos ON alumnos.id = pronosticos.alumno_id JOIN usuarios ON usuarios.id = alumnos.usuario_id")
  
  validates_uniqueness_of :alumno_id, :scope => [:materia_id, :semestre_id]  

  MinNumberPerSemester = 6 # Número de materias a pronosticar para considerar que el pronostico fue completo  

  def self.stats_for_semestre(semestre_id, usuario)
    stats = {}
    alumnos = Pronostico.alumnos_for_semester(semestre_id) 
		unless alumnos.empty?    
		  alumnos.filtro_director(usuario).each do |alumno|
        stats[alumno.carrera.siglas] = stats[alumno.carrera.siglas].nil? ? 1 : stats[alumno.carrera.siglas] + 1
      end
    end
    stats
  end
  
  # Regresa los alumnos que realizaron sus pronosticos en 
  # el semestre con id +semestre_id+
  def self.alumnos_for_semester(semestre_id)
    alumno_ids = Pronostico.select(:alumno_id).where(:semestre_id => semestre_id).group(:alumno_id).map { |pronostico| pronostico.alumno_id }
		alumno_ids += ProgramaInternacional.select(:alumno_id).where(:semestre_id => semestre_id).map { |programa| programa.alumno_id }
    if alumno_ids.any?
      @alumnos = Alumno.where("id IN (?)", alumno_ids)
    else
      @alumnos = []
    end
    @alumnos
  end
  
  def self.tempfile_path
    File.join Rails.root, 'tmp'
  end
  
  def self.make_csv_file(semestre_id)
    file = File.open( File.join(Alumno.tempfile_path, "pronosticos_#{Time.now.to_i}.csv"), 'wb')
    file.write "Clave, Nombre Materia, Pronostico\n"
    Pronostico.total_count.where(:semestre_id => semestre_id).each do |pronostico|
      file.write "#{pronostico.clave}, #{pronostico.nombre}, #{pronostico.num}\n"
    end      
    file.close
    file.path    
  end
  


end 

app/controllers/alumnado/pronosticos_controller.rb
class Alumnado::PronosticosController < ApplicationController
  before_filter :require_session
  MAX_MATERIAS = 7 #Cuantas materias puede pronosticar un alumno para un semestre

  def index
    @alumno = Alumno.where(:usuario_id => @user.id).first

    if @alumno.has_predictions_for?(next_semester)
      redirect_to :action => :thank_you and return
    else
      @materias = @alumno.possible_subjects
      @max_items = MAX_MATERIAS
    end
  end

  def thank_you
		@alumno = Alumno.where(:usuario_id => @user.id).first
    @semestre = next_semester
		@content = @alumno.predictions_by_semestre_id(@semestre.id)
		@programa_internacional = @alumno.programa_internacional_by_semestre_id(@semestre.id)
		@candidato = @alumno.candidato_by_semestre_id(@semestre.id)
  end

  def create
    require_post do
      success = false
			@alumno = Alumno.select('id').where(:id => params[:alumno_id]).first
			if @alumno
				@semestre = next_semester
				if params[:programa_internacional] == 'true'
					ProgramaInternacional.create!(:alumno_id => @alumno.id, :semestre_id => @semestre.id)
					success = true
		    elsif params[:checked_items] && params[:checked_items].length <= MAX_MATERIAS
		      params[:checked_items].each do |materia_id|
		        Pronostico.create!(:alumno_id => @alumno.id, :semestre_id => @semestre.id, :materia_id => materia_id)
		      end
					if params[:candidato] == 'true'
						Candidato.create!(:alumno_id => @alumno.id, :semestre_id => @semestre.id)
					end
					success = true
				end
      end
      render :json => {:success => success}
    end
  end

  ##Regresar a administrador
    def changetoadmin
      session[:user_id] = session[:true_user_id]
      session.delete(:true_user_id)
      redirect_to "/admin"
    end


end

app/controllers/pronosticos_controller.rb
class PronosticosController < ApplicationController
  before_filter :require_admin
	before_filter :set_usuario, :only => [:list_pronosticos, :list_alumnos, :pending_students, :incomplete_students, :list_programas_internacionales, :list_candidatos]

  MAX_MATERIAS = 7 #Cuantas materias puede pronosticar un alumno para un semestre
  PRONOSTICOS_PER_PAGE = 30
  
  def index
    get_plans
    get_semesters
  end  
  
  def search
    
  end 
  
  def list_pronosticos
    require_post do 
      set_page 		
		  set_semestre_id
      contents = Pronostico.total_count.where(:semestre_id => params[:semestre_id]).limit(PRONOSTICOS_PER_PAGE).offset(PRONOSTICOS_PER_PAGE * params[:page])                        
      total = Pronostico.select("COUNT(*) AS num, pronosticos.materia_id").where(:semestre_id => params[:semestre_id]).group("pronosticos.materia_id")
      
      if params[:plan_id] 
        contents = contents.by_plan_id params[:plan_id]
        total = total.by_plan_id params[:plan_id]
      end

			if @usuario.is_director?
				contents = contents.by_plan_id Plane.por_director(@usuario.id)
        total = total.by_plan_id Plane.por_director(@usuario.id)
			end
      
      render :json => {
        :contents => contents,
        :total    => total.length,
        :per_page => PRONOSTICOS_PER_PAGE
      }
    end
  end

	def list_candidatos
    require_post do 
      set_page 		
		  set_semestre_id
			contents = Alumno.candidate_for params[:semestre_id]
      
      if params[:plan_id] 
        contents = contents.where("plane_id = (?)", params[:plan_id])
      end

			if @usuario.is_director?
				contents = contents.where("plane_id IN (?)", Plane.por_director(@usuario.id))
			end

      render :json => {
        :contents => contents,
        :total    => contents.length,
        :per_page => PRONOSTICOS_PER_PAGE
      }
    end
  end

	def list_programas_internacionales
    require_post do 
      set_page 		
		  set_semestre_id
			contents = Alumno.with_international_program_for params[:semestre_id]
      
      if params[:plan_id] 
        contents = contents.where("plane_id = (?)", params[:plan_id])
      end

			if @usuario.is_director?
				contents = contents.where("plane_id IN (?)", Plane.por_director(@usuario.id))
			end

      render :json => {
        :contents => contents,
        :total    => contents.length,
        :per_page => PRONOSTICOS_PER_PAGE
      }
    end
  end
  
  def list_alumnos
    require_post do 
      set_page
      set_semestre_id
      contents = Pronostico.with_alumno.where(:materia_id => params[:materia_id], :semestre_id => params[:semestre_id]).limit(PRONOSTICOS_PER_PAGE).offset(PRONOSTICOS_PER_PAGE*params[:page])
			total = Pronostico.select("COUNT(*) AS num").where(:materia_id => params[:materia_id], :semestre_id => params[:semestre_id])

			if @usuario.is_director?
				contents = contents.by_plan_id Plane.por_director(@usuario.id)
        total = total.by_plan_id Plane.por_director(@usuario.id)
			end
			
      render :json => {
        :contents => contents,
        :total    => total[0][:num],
        :per_page => PRONOSTICOS_PER_PAGE
      }
    end
  end
  
  def download_csv
    set_semestre_id
    path = Pronostico.make_csv_file(params[:semestre_id])
    send_file path, :type => "application/csv"
  end
  
  def pending_students
    @semestre = next_semester
    @pending_students = Alumno.without_predictions_for(@semestre.id).filtro_director(@usuario)
  end
  
  def incomplete_students
    @semestre = next_semester
    @incomplete_students = Alumno.with_incomplete_predictions_for(@semestre.id).filtro_director(@usuario)
  end

  def international_programs
		get_plans
		get_semesters
		@semestre = next_semester
  end
  
	def candidates
    get_plans
		get_semesters
		@semestre = next_semester
  end

  def show 
    @materia = Materia.find(params[:id])
    get_semesters
  end
  
  private
    def get_plans
			usuario = Usuario.find session[:user_id]
			if usuario.is_director?
				@planes = Plane.por_director(usuario.id).map do |id|
					plan = Plane.find(id)
					[plan.nombre, plan.id]
				end
			else			
				@planes = Plane.order(:nombre).map do |plan|
					[plan.nombre, plan.id]
				end
			end
    end

    def set_usuario
			@usuario = Usuario.find session[:user_id] 
		end
    
    def set_page
      params[:page] = params[:page].nil? ? 0 : params[:page].to_i
    end
    
    def set_semestre_id
      params[:semestre_id] = params[:semestre_id].nil? ? next_semester.id : params[:semestre_id]
    end
    
    def get_semesters
      @semestres = Semestre.order("fecha_inicio DESC")
    end
end

app/helpers/alumnado/pronosticos_helper.rb
module Alumnado::PronosticosHelper
end

app/helpers/pronosticos_helper.rb
module PronosticosHelper
  def semestre_text(i)
    [ 
      'Remediales','Primer semestre',
      'Segundo semestre','Tercer semestre',
      'Cuarto semestre','Quinto semestre',
      'Sexto semestre','Septimo semestre',
      'Octavo semestre','Noveno semestre',
      'Decimo semestre'
    ][i]
  end
end

app/views/alumnado/pronosticos/already_completed.html.erb
<div id="main_header">
	<%= render :partial => 'shared/main_header', :locals => {:title => 'Pronósticos'}%>
</div>
<div id="main_content">
    <div id="content" class="no_border">
        <div id="content_header">
			<div id="content_header_left">
				<h2>¡Gracias!</h2>
			</div>
			<div class="clr"></div>
		</div>
        <p> 
            Tus pronósticos para el semestre <span class="blue"> <%= semester_name @semestre.fecha_inicio, @semestre.fecha_fin %> </span> ya han sido registrados, si haz cambiado de opini&oacute;n, por favor, <%= link_to 'contáctanos', 'mailto:gerardo.cervera@itesm.mx' %>
        </p>
    </div>
    <div class="clr"></div>
</div>

app/views/alumnado/pronosticos/index.html.erb
<%= javascript_include_tag 'dialog' %>
<script type="text/javascript">
	(function(){
		var materias_container;
		var options_container;	
		var continue_btn;
		var checked_items;
		var checked_items_number = 0;
		var programa_internacional;
		var candidato;
		var success_url = '<%= alumnado_pronosticos_thank_you_url %>';
		var max_items = <%= @max_items %>;
		$(function(){
			materias_container = $('#materias_container');
			options_container = $('#options_container');
			continue_btn = $('#continue_btn').click(function(e){
				e.preventDefault();
				checked_items = [];
				materias_container.find('input[type="checkbox"].checked').each(function(){
					checked_items.push($(this).val());
				});
				$.post(
					'<%= url_for :controller => :pronosticos, :action => :create %>',
					{						
						'checked_items': checked_items,
						'programa_internacional': programa_internacional,
						'candidato': candidato,
						'alumno_id': '<%= @alumno.id %>'				
					},
					function(data) {
						if(data.success) {
							window.location = success_url;
						}	
						else {
							$.dialog({
								'title': 'Oops!',
								'msg': 'Se ha producido un error, intenta más tarde	'
							});
						}
					}
				);
				
			});
			materias_container.find('.materia_checkbox').change(function(e){				
				if($(this).is(':checked') && checked_items_number < max_items) {
					++checked_items_number;
					$(this).addClass('checked');
					$(this).parent().parent().addClass('selected_row');							
				}
				else if(!$(this).is(':checked')){
					--checked_items_number;							
					$(this).removeClass('checked');
					$(this).parent().parent().removeClass('selected_row');
				}
				else {
					$(this).attr('checked',false);
					$.dialog({
						title: 'Error',
						msg: 'Por favor selecciona hasta ' + max_items + ' materias',
						min_height: 100
					});
				}
			});
			options_container.find('.programa_checkbox').change(function(e){
				if($(this).is(':checked')) {
					$('#materias_container').hide();
					programa_internacional = true;
					candidato = false;
					$('.candidato_checkbox').attr('checked', false);			
				}
				else {
					$('#materias_container').show();
					programa_internacional = false;				
				}
			});
			options_container.find('.candidato_checkbox').change(function(e){
				if($(this).is(':checked')) {
					candidato = true;
					programa_internacional = false;
					$('.programa_checkbox').attr('checked', false);
					$('#materias_container').show();
				}
				else {
					candidato = false;				
				}
			});
		});
	})(jQuery);
</script>
<div id="main_header">
	<%= render :partial => 'shared/main_header', :locals => {:title => 'Pronósticos'}%>
</div>
<div id="main_content">	
	<div id="sidebar">
		<h3 class="blue">Instrucciones</h3>
		<p class="guidelines">
			A la derecha encontrarás una lista de las materias que podrías cursar
			el siguiente semestre, dependiendo de tu historial académico y de acuerdo a 
			la regla de los 3 semestres. 
		</p><br />		
		<p class="guidelines">
			Por favor selecciona hasta <%= @max_items %> materias y presiona continuar. Si serás candidato
			a graduar, marca la casilla y selecciona tus materias.					
		</p>
		</p><br />		
		<p class="guidelines">
			Si harás un programa internacional el próximo semestre, marca la casilla correspondiente 
			y no selecciones materias.		
		</p>
		<div class="hr_light_10"></div>
		<h3 class="blue">Notas</h3>
		<p class="guidelines">
			Las materias que pronostiques no necesariamente serán las que curses el
			siguiente semestre, esto sólo nos ayuda a determinar qué materias abrir.
		</p>
	</div>
	<div id="content">
		<div id="content_header">
			<div id="content_header_left">
				<h2>Pronósticos</h2>
			</div>
			<div id="content_header_right">
				<%= link_to 'Continuar', '#', :class => 'blue_btn', :id => 'continue_btn' %>
			</div>
			<div class="clr"></div>
		</div>
		
		<div id="options_container">
			<%= check_box_tag 'programa_internacional', 1, false, {:class => :programa_checkbox} %>
			<label>Programa internacional</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= check_box_tag 'candidato', 1, false, {:class => :candidato_checkbox} %>
			<label>Candidato a graduar</label>
		</div>

		<table class="custom_table" id="materias_container">
			<tbody>
				<% semestre = -1 %>
				<% @materias.each do |materia| %>
					<% if materia.semestre_for(@alumno.plane_id) != semestre %>
						<% semestre = materia.semestre_for(@alumno.plane_id) %>
						<tr class="separator">
							<td colspan="3"><%= semestre_text semestre %></td>
						</tr>
					<% end %>
					<tr>
						<td><%= check_box_tag materia.id, materia.id, false, {:class => :materia_checkbox	} %></td>
						<td><%= materia.clave %></td>
						<td><%= materia.nombre %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<div class="clr"></div>
</div>
			

app/views/alumnado/pronosticos/thank_you.html.erb
<div id="main_header">
	<%= render :partial => 'shared/main_header', :locals => {:title => 'Pronósticos'}%>
</div>
<div id="main_content">
    <div id="content" class="no_border">
        <div id="content_header">
			<div id="content_header_left">
				<h2>¡Gracias!</h2>
			</div>
			<div class="clr"></div>
		</div>
        <p> 
            Tus pronósticos para el semestre <span class="blue"> <%= semester_name @semestre.fecha_inicio, @semestre.fecha_fin %> </span> ya han sido registrados, si has cambiado de opini&oacute;n, por favor, <%= link_to 'contáctanos', 'mailto:gerardo.cervera@itesm.mx' %>.
        </p>

				<br>
				<% if @programa_internacional %>
					<h3>Programa internacional</h3>
				<% else %>
					<h3>Tus pron&oacute;sticos son: </h3>
					<% if @candidato %>
						<br/><p>Candidato a graduar<p>
					<% end %>
					<table class="custom_table" id="pronosticos_container">
						<tbody>
							<% @content.each do |materia| %>
								<tr>
									<td>
										<%= materia.clave %>
									</td>
									<td>
										<%= materia.nombre %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				<% end %>		
    		<div class="clr"></div>
    		</div>
    </div>
    <div class="clr"></div>
</div>